Naming convention, adding data from website, and CsI test
ORNL-CEES/thermochimica pull request #159
Opened 2024-05-01 19:42 UTC by aidanfitz

2024-05-02 02:53 UTC, parikshitbajpai reviewed
Looks good. Do we have permission to share all the data files that are new?

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Kaye-NobleMetals.dat
Should rename it similar to other files and use elements instead of `NobleMetals`

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Kaye-ternaryMiscibility.dat
Same as previous

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Liang-AlMg.dat
How about `AlMg-Liang.dat`? If we do this for all the files we should get the data files sorted by elements and the author names will still be acknowledged.

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Pham-CsI.dat
`CsI-Pham.dat`?

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Dupin-ZrH.dat
`ZrH-Dupin.dat`

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Kang-CuFeC.dat
`CuFeC-Kang.dat`?

2024-05-02 17:05 UTC, parikshitbajpai commented on data/Kaye-MoPdRuRhTc.dat
`MoPdRuRhTc-Kaye.dat`

2024-05-05 03:12 UTC, parikshitbajpai commented on README.md
> +sudo apt-get update
```suggestion
sudo apt update && sudo apt upgrade
```

2024-05-05 03:17 UTC, parikshitbajpai requested changes

2024-05-05 03:17 UTC, parikshitbajpai commented on python/pseudoBinaryPhaseDiagramGUI.py
> +    def __init__(self, parent, datafile, nElements, elements, active,scrollable=True):
```suggestion
    def __init__(self, parent, datafile, nElements, elements, active, scrollable=True):
```

2024-05-05 03:17 UTC, parikshitbajpai commented on python/pseudoBinaryPhaseDiagramGUI.py
> +            self.sgw = sg.Window(f'Phase Diagram Setup: {os.path.basename(self.datafile)}', self.layout,resizable=True,size=(600, 800),location = [400,0], finalize=True)
```suggestion
            self.sgw = sg.Window(f'Phase Diagram Setup: {os.path.basename(self.datafile)}', self.layout, resizable=True, size=(600,800), location = [400,0], finalize=True)
```

2024-05-05 03:17 UTC, parikshitbajpai commented on python/pseudoBinaryPhaseDiagramGUI.py
> +            elemLayout = [sg.Column(elem1Layout,vertical_alignment='t', scrollable = True, vertical_scroll_only = True,  size=(200, 100),expand_y = True),
```suggestion
            elemLayout = [sg.Column(elem1Layout, vertical_alignment='t', scrollable = True, vertical_scroll_only = True, size=(200,100), expand_y = True),
```

2024-05-05 03:17 UTC, parikshitbajpai commented on python/pseudoBinaryPhaseDiagramGUI.py
> +                          sg.Column(elem2Layout,vertical_alignment='t', scrollable = True, vertical_scroll_only = True, size=(200, 100), expand_y = True)]
```suggestion
                          sg.Column(elem2Layout, vertical_alignment='t', scrollable = True, vertical_scroll_only=True, size=(200,100), expand_y=True)]
```

2024-05-06 17:06 UTC, aidanfitz commented
Sorry for the late response. I will get on it and make sure your suggestions will be used. I updated the file names to system-owner.dat. And all files are from the tutorial, excluding one that we cannot post there should be no need to worry on that end.

2024-05-20 01:07 UTC, merged